name: update-all-by-timezone
on:
  schedule:
    - cron: '0 * * * *' # updates all users per timezone
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API route to update all users' habits at midnight
        run: |
          curl --request POST \
          --url 'https://atomic-t3.vercel.app/api/cron' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'